### PR TITLE
Update readme with link to docs & SPI options

### PR DESCRIPTION
**Pull request by elcritch**
I noticed my lab tech couldn't figure out setting the SPI bus speed. This change should help new people find the docs and set the options.

### CODE REVIEW

**Comment by fhunleth** [comment]
This comes up frequently. I'd like to update all of my projects to make finding the docs more obvious.

Do you think that adding a badge like [Hex version](https://hexdocs.pm/circuits_spi/Circuits.SPI.html) to the top of the README.md would have helped him or her?

**Comment by fhunleth** [comment]
I'm thinking that text updates are useful too. I'm just looking for a something that I can copy/paste across all projects.

**Comment by elcritch** [comment]
> Do you think that adding a badge like Hex version to the top of the README.md would have helped him or her? 

I'm a fan of the badge! For people really new to IoT dev and/or programming Elixir just a docs badge doesn't seem to help quite as much from what I've seen, as they aren't familiar with the idea of badges at first. 

I'd say for just the main Circuits.{SPI/GPIO/I2C} projects that having a badge along with a short section about setting extra options and/or a linking to the relevant docs, if mainly for non-programmers.

**Comment by fhunleth** [comment]
Ok. #31 adds the badge. 

I think that the text in this PR works better as a FAQ entry. The question would be "How do I set the speed of the SPI bus?". I'd make it the second FAQ entry since finding the SPI bus seems even more basic.

Could you make the edits and re-push?

**Comment by elcritch** [comment]
Sure, that makes sense. I'll edit and repush.

**Comment by fhunleth** [comment]
Thanks! I made a couple minor edits, squashed and manually merged.

**Pull request closed without merging**
